### ISSUE TITLE
[Fixed] 달력의 이전 달 날짜 나올 때 항상 31일까지 나오는 문제

### ISSUE THREAD

**Issue by SeongbinJo** [nilworks/timestone#2]
## 어떤 버그인가요?

> 달력에 1일의 요일에 맞게 이전 달의 날짜들이 출력되어야하는데 출력되는 날짜의 마지막이 항상 31일로 출력되는 버그
![스크린샷 2024-12-23 오후 10 36 12](https://github.com/user-attachments/assets/c889439d-dce3-4db2-8462-ec01edc0aa39)
(9월달은 30일까지 있지만 31일까지로 나옴. 1~12월 전부 31일로 동일하게 나옴)

## 어떤 상황에서 발생한 버그인가요?

> 
```
// View
ForEach((0..<prevDaysCount).reversed(), id: \.self) { i in
      CalendarCellView(cellTitle: countPrevMonthDays - i, currentMonthDay: false)
}

struct CalendarCellView: View {
    @State var cellTitle: Int = 0
    var currentMonthDay: Bool = true
    
    var body: some View {
        VStack {
            Text("\(cellTitle)")
                .foregroundStyle(currentMonthDay ? Color.black : Color.gray)
        }
    }
}


// ViewModel
func numberOfDaysPrevMonth() -> Int {
    let prevMonth = Calendar.current.date(byAdding: .month, value: -1, to: month)!
    print("이전 달의 날짜 개수 : \(Calendar.current.range(of: .day, in: .month, for: prevMonth)?.count ?? 0)")
    return Calendar.current.range(of: .day, in: .month, for: prevMonth)?.count ?? 0
}
```

## 예상 결과

> 이전 달의 마지막 날에 맞게끔 Cell이 출력되었어야함. 
Ex) 이전 달이 24년 9월일 경우, '29 30'

## 해결
![스크린샷 2024-12-23 오후 10 42 43](https://github.com/user-attachments/assets/e68b7717-6772-4c86-8926-8312204cbbf3)

> CalendarCellView의 cellTitle이 @State로 선언되어있었다...;;
(@State는 뷰가 다시 렌더링 되어도 값을 유지함)

[틀린 혹은 잘못된 정보가 있다면 댓글 부탁드립니다.]

**Comment by rmfls0606** [comment]
@State눈 뷰가 다시 렌더링 되어도 값을 유지하는 것을 다시한번 상기시킬 수 있었습니다. 고생하셨습니다~!
